// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      coffee: {
        app: {
          src: ['coffee/*.coffee'],
          dest: 'temp'
        }
      }
    });
    require('load-grunt-tasks')(grunt);
    grunt.registerTask('default', ['watch']);
    return grunt.registerTask('thing', ['coffee:app']);
  };

}).call(this);
